#pragma once
#include <Windows.h>
#include <initguid.h>
#include <wincrypt.h>
#include "mssip.h"
#include <basetyps.h>
#include <ATLBASE.h>
#include <ATLCONV.H>
#if defined(NTDDI_WIN10_VB) && NTDDI_VERSION > NTDDI_WIN10_VB
#include <ActivityCoordinatorTypes.h>
#endif
#include <AudioEngineBaseAPO.h>
#include <BthLEDef.h>
#include <CHPtrArr.h>
#include <CHString.h>
#include <ComputeDefs.h>
#include <D2D1EffectAuthor.h>
#include <D2DBaseTypes.h>
#include <D2DErr.h>
#include <DWrite.h>
#include <DWrite_1.h>
#include <DWrite_2.h>
#include <DirectXMath.h>
#include <EapTypes.h>
#include <FunctionDiscoveryKeys_devpkey.h>
#include <GL/gl.h>
#include <GenLex.h>
#include <IMessageDispatcher.h>
#include <IVectorChangedEventArgs.h>
#include <InputEventFlags.h>
#include <Inspectable.h>
#include <OPathLex.h>
#include <ObjPath.h>
#include <Objsafe.h>
#include <POPPACK.H>
#include <PSHPACK1.H>
#include <PerceptionDeviceCore.h>
#include <PhotoAcquireProperties.h>
#include <PhysicalMonitorEnumerationAPI.h>
#include <Polarity.h>
#include <PropKeyDef.h>
#include <ProvExce.h>
#include <SCSISCAN.H>
#include <SPError.h>
#ifdef  _CRT_SECURE_NO_WARNINGS 
#include <SPHelper.h>
#endif
#include <SensorsApi.h>
#include <SensorsStructures.h>
#include <Shellapi.h>
#include <SpecStrings.h>
#include <TPCError.h>
#include <TraceLoggingActivity.h>
#include <TraceLoggingProvider.h>
#include <UIAutomationClient.h>
#include <UIAutomationCore.h>
#include <UIAutomationCoreApi.h>
#include <UIRibbonKeyDef.h>
#include <VFWMSGS.H>
#include <WbemTime.h>
#include <WcnDevice.h>
#include <WcnTypes.h>
#include <WinDef.h>
#include <WinHvPlatformDefs.h>
#include <WinString.h>
#include <Windows.Media.Protection.PlayReadyResults.h>
#include <Windows.Media.Streaming.h>
#include <Windows.System.h>
#include <Windows.UI.h>
#include <Windows.graphics.h>
#include <Windows.ui.composition.h>
#include <WlanIhvTypes.h>
#include <WlanTypes.h>
#include <WpcApi.h>
#include <WpcEvent.h>
#include <accctrl.h>
#include <aclui.h> 
#include <activation.h>
#include <activationregistration.h>
#include <activdbg.h>
#include <activprof.h>
// #include <adogpool.h> // Cannot be used directly
#include <adtgen.h>
#include <ahadmin.h>
#include <algorithm>
#include <amaudio.h>  
#include <amvideo.h> 
#include <apiquery2.h>
#include <apiset.h>
#include <apisetcconv.h>
#include <appmodel.h>
#if defined (_M_ARM64) || defined(_M_HYBRID_X86_ARM64) || defined(_M_ARM64EC)
#include <arm64_neon.h>
#include <arm_neon.h>
#endif
#include <array>
#include <assert.h>
#include <asyncinfo.h>
#include <atomic>
#include <audevcod.h>   // audio filter device error event codes"
#include <audiosessiontypes.h> // For AUDIO_STREAM_CATEGORY"
#include <austream.h>
#include <authz.h>
#include <avrt.h>
#include <axextendenums.h>
#include <basetsd.h>
#include <bcrypt.h>
#include <bthdef.h>
#include <ccomplex>
#include <cderr.h>
#include <certadm.h>
#include <certbcli.h>
#include <certcli.h>
#include <certenc.h>
#include <certexit.h>
#include <certif.h>
#include <certmod.h>
#include <certpol.h>
#include <certview.h>
#include <cfg.h>
#include <cfgmgr32.h>
#include <cguid.h>
#include <charconv>
#include <clfs.h>

#include <clfsmgmt.h>
#include <clfsw32.h>
#include <clusapi.h>
#include <cmath>
#include <codecapi.h>
#include <colordlg.h>
#include <combaseapi.h>
#include <comcat.h>
#include <comdef.h>
#include <coml2api.h>
#include <commctrl.h>
#include <commctrl.rh>
#include <commdlg.h>
#include <compare>
#include <complex.h>
#include <compstui.h>
#include <concurrencysal.h>
#include <consoleapi.h>
#include <consoleapi2.h>
#include <consoleapi3.h>
#include <cor.h>
#include <corecrt.h>
#include <corecrt_io.h>
#include <corecrt_malloc.h>
#include <corecrt_math.h>
#include <corecrt_math_defines.h>
#include <corecrt_memcpy_s.h>
#include <corecrt_memory.h>
#include <corecrt_search.h>
#include <corecrt_share.h>
#include <corecrt_startup.h>
#include <corecrt_stdio_config.h>
#include <corecrt_wconio.h>
#include <corecrt_wctype.h>
#include <corecrt_wdirect.h>
#include <corecrt_wio.h>
#include <corecrt_wprocess.h>
#include <corecrt_wstdio.h>
#include <corecrt_wstdlib.h>
#include <corecrt_wstring.h>
#include <corecrt_wtime.h>
#include <corhdr.h>
#include <coroutine>
#include <crtdbg.h>
#include <crtdefs.h>
#include <cstddef>
#include <cstdint>
#include <cstring>
#include <ctgmath>
#include <ctype.h>
#include <d2d1.h>
#include <d2d1_1.h>
#include <d2d1_1helper.h>
#include <d2d1_2.h>
#include <d2d1_2helper.h>
#include <d2d1_3.h>
#include <d2d1_3helper.h>
#include <d2d1effects.h>
#include <d2d1effects_1.h>
#include <d2d1effects_2.h>
#include <d2d1helper.h>
#include <d2d1svg.h>
#include <d3d10_1.h>
#include <d3d9.h>
//#include <d3dcaps.h>
#include <d3dcommon.h>
#include <d3dhal.h>
//#include <d3dkmdt.h>
#include <d3dnthal.h>
#include <d3dtypes.h>
//#include <d3dukmdt.h>
#include <daogetrw.h>
#include <datetimeapi.h>  // Datetime APISET dependencies"
#include <dbdaoid.h>
#include <dbdaoint.h>
#include <dcommon.h>
//#include <dcompanimation.h> // for IDirectCompositionAnimation interface"
//#include <dcomptypes.h>     // for CompositionSurfaceType"
#include <dde.h>
#include <dde.rh>
#include <ddeml.h>
#include <ddraw.h>
//#include <ddrawi.h>
#include <ddrawint.h>
#include <ddstream.h>
#include <debugapi.h>
#include <devfiltertypes.h>
#include <devioctl.h>
//#include <devpkey.h>
#include <devpropdef.h>
#include <devquerydef.h>
#include <diagnosticdataquerytypes.h>
#include <diskguid.h>
#include <dlgs.h>
#include <dot1x.h>
#include <dpa_dsa.h>
#include <dpapi.h>
//#include <dpx1.h>
#include <driverspecs.h>
#include <dsound.h>
#include <dsparse.h>
#include <dvdevcod.h>   // DVD error event codes"
//#include <dxgi.h>
//#include <dxgi1_5.h>    // for DXGI_ALPHA_MODE, DXGI_HDR_METADATA_TYPE"
#include <dxgiformat.h>
#include <dxgitype.h>   // for DXGI_RATIONAL"
#include <edevdefs.h>  
#include <eh.h>
#include <emmintrin.h>
#include <encdec_enums.h>
#include <enclaveapi.h>
#if defined(NTDDI_WIN10_VB) && NTDDI_VERSION > NTDDI_WIN10_VB
#include <enclaveium.h>
#endif
#include <errhandlingapi.h>
#include <errno.h>
#include <errors.h>     // HRESULT status and error definitions"
#include <evcode.h>     // event code definitions"
#include <eventtoken.h>  // used for EventRegistrationToken"
#include <evntcons.h>
#include <evntprov.h>
#include <evntrace.h>
#include <exception>
#include <excpt.h>
//#include <exdisp.h>
//#include <experimental/coroutine>
#include <exposeenums2managed.h>
#include <fdi_fci_types.h>
//#include <features.h>
#include <fibersapi.h>
#include <fileapi.h>
#include <fileapifromapp.h>
#include <float.h>       // float bounds"
#include <fltUserStructures.h>
#include <format>
#include <guiddef.h>    // REVIEW: or just redefine GUID here"
#include <handleapi.h>
#include <heapapi.h>
#include <hstring.h>
//#include <http.h>
#include <idispids.h>
//#include <iedial.h>
#include <ifdef.h>
#include <ifmib.h>
#include <ime_cmodes.h>
#include <imm.h>
#include <immintrin.h>
#include <in6addr.h>
#include <inaddr.h>
//#include <indexsrv.h>
#include <interlockedapi.h>
#include <intrin.h>
#include <intsafe.h>
#include <ioapiset.h>
#include <ipexport.h>
#include <ipifcons.h>
#include <ipmib.h>
#include <iprtrmib.h>
#include <iptypes.h>
#include <ipv6prefast.h>
#include <ipxconst.h>
#include <ipxrip.h>
#include <ipxsap.h>
#include <ipxtfflt.h>
#include <isguids.h>            // internet shortcut GUIDs"
#include <issper16.h>
#include <iterator>
#include <jobapi.h>
#include <jobapi2.h>
#include <joystickapi.h>
//#include <jsrt9.h>
#include <kernelspecs.h>
#include <knownfolders.h>
#include <ks.h>
#include <ksmedia.h>
#include <ktmtypes.h>
#include <l2cmn.h>
#include <libloaderapi.h> // LibLoader Apiset dependencies"
#include <limits.h>
#include <limits>
#include <lmaccess.h>   // Access, Domain, Group and User classes"
#include <lmalert.h>    // Alerter"
#include <lmapibuf.h>   // NetApiBuffer class"
#include <lmaudit.h>    // NetAudit class"
#include <lmconfig.h>   // NetConfig class"
#include <lmcons.h>     // LAN Manager common definitions"
#include <lmerr.h>      // LAN Manager network error definitions"
#include <lmerrlog.h>   // NetErrorLog class"
#include <lmjoin.h>     // NetJoinDomain class"
#include <lmmsg.h>      // Message class"
#include <lmremutl.h>   // Remote Utility class"
#include <lmrepl.h>     // Replicator class"
#include <lmserver.h>   // Server class"
#include <lmshare.h>    // Connection, File, Session and Share classes"
#include <lmsname.h>
#include <lmstats.h>    // NetStats class"
#include <lmsvc.h>      // Service class"
#include <lmuse.h>      // Use class"
#include <lmuseflg.h>                   // Deletion force level flags"
#include <lmwksta.h>    // Workstation class"
#include <lsalookup.h>
#include <lzexpand.h>
#include <malloc.h>             // calloc()"
#include <map>
#include <math.h>           // For log10()"
#include <mbstring.h>
#include <mciapi.h>
#include <mcx.h>
#include <mdcommsg.h>
#include <mdmsg.h>
#include <memory.h>
#include <memory>
#include <memoryapi.h>
#include <minappmodel.h>
#include <minidumpapiset.h>
#include <minschannel.h>
#include <minwinbase.h>
#include <minwindef.h>
#include <mmeapi.h>
#include <mmiscapi.h>
#include <mmiscapi2.h>
#include <mmreg.h> 
#include <mmstream.h>
#include <mmsyscom.h> // mm common definitions"
#include <mmsystem.h>
#include <mprapi.h>
#include <mprapidef.h>
#include <msacm.h>
#include <mscat.h>
#include <mshtmcid.h>
#include <mshtmdid.h>
#include <mstcpip.h>
#include <mswsockdef.h>

#include <namedpipeapi.h>
#include <naptypes.h>
#include <nb30.h>
#include <ncrypt.h>
#include <ndattrib.h>
#if defined(NTDDI_WIN10_VB) && NTDDI_VERSION > NTDDI_WIN10_VB
#include <ndis/hashtypes.h>
#include <ndis/ioctltypes.h>
#include <ndis/nbluro.h>
#include <ndis/ndisport.h>
#include <ndis/nicswitchtypes.h>
#include <ndis/objectheader.h>
#include <ndis/offloadtypes.h>
#include <ndis/oidtypes.h>
#include <ndis/types.h>
#endif
#include <ndis/version.h>
#include <ndkinfo.h>

//#include <netioapi.h>
#include <nettypes.h>
#include <new.h>
#include <new>
#include <nldef.h>
#include <no_sal2.h>
#include <ntddndis.h>
#include <ntddscsi.h>
#include <ntddstor.h> // STORAGE_DEVICE_DESCRIPTOR and similiar"
#if defined(NTDDI_WIN10_VB) && NTDDI_VERSION > NTDDI_WIN10_VB
#include <ntioring_x.h>
#endif
#include <ntverp.h>
#include <oaidl.h>
#include <objbase.h>           // Windows COM declarations"
#include <objerror.h>
#include <objidl.h> // for IStream"
#include <ocidl.h>
//#include <ole.h>
#include <ole2.h>      // for DECLARE_INTERFACE_ and HRESULT"
#include <oleauto.h>
#include <olectl.h>
#include <oleidl.h>
#include <optional>
#include <ostream>
#include <packoff.h>
#include <packon.h>
#include <pchannel.h>
#include <pciprop.h>
#include <playsoundapi.h>
#include <pmmintrin.h>
#include <poclass.h>
#include <powerbase.h>
#include <powersetting.h>
//#include <printoem.h>
//#include <prntfont.h>
#include <processenv.h>
#include <processthreadsapi.h>
#include <processtopologyapi.h>
#include <profileapi.h>
#include <profinfo.h>
#include <propapi.h>
#include <propidl.h>
#include <propidlbase.h>
#include <propkey.h>
//#include <propvarutil.h>  
//#include <provider.h>
#include <prsht.h>
#include <pshpack2.h>
#include <pshpack4.h>
#include <pshpack8.h>
#include <qos.h>
#include <qosobjs.h>
#include <ras.h>
#include <realtimeapiset.h>
#include <reason.h>             // get the public reasons"
//#include <restrictedErrorInfo.h>
#include <roapi.h>
#include <rometadataresolution.h>
#include <rpc.h>
#include <rpcasync.h>
#include <rpcdce.h>
#include <rpcdcep.h>

#include <rpcndr.h> // used for boolean"
#include <rpcnsi.h>
#include <rpcnsip.h>
#include <rpcnterr.h>
#include <rpcsal.h>
#include <rtutils.h>
#include <sal.h>
//#include <sapi.h>
//#include <sapiddk.h>
#include <schannel.h>
#include <schedule.h>
#include <schnlsp.h>
#include <sdkddkver.h>
#include <search.h>
//#include <secext.h>
#include <securityappcontainer.h>
#include <securitybaseapi.h>
#include <set>
#include <setjmp.h>
#include <setupapi.h>
#include <sherrors.h>
#include <shtypes.h>
#include <sipbase.h>
#include <smmintrin.h>
#include <snmp.h>
#include <source_location>
#include <span>
#include <spapidef.h>
#include <specstrings_strict.h>
#include <specstrings_undef.h>
#include <sqlext.h>
#include <stdarg.h>
#ifdef ISSP_LEVEL
#include <sspi.h>
#endif
#include <stdbool.h>
#include <stddef.h>
#include <stdexcept>
#include <stdint.h>
#include <stdio.h>  
#include <stierr.h>
#include <stireg.h>
#include <stllock.h>
//#include <stm.h>
#include <stralign.h>
#include <string.h> 
#include <string>
#include <string_view>
#include <stringapiset.h>    
//#include <strmif.h>     // Generated IDL header file for streams interfaces"
///#include <strsafe.h>
#include <suppress.h>
//#include <swdevicedef.h>
#include <synchapi.h>
#include <sys/stat.h>
#include <sys/types.h>
#include <sysinfoapi.h>
#include <systemtopologyapi.h>
//#include <tapi.h>
#include <tapi3err.h>
#include <tchar.h>
#include <tcpestats.h>
#include <tcpmib.h>
#include <thread>
#include <threadpoolapiset.h>
#include <threadpoollegacyapiset.h>
#include <time.h>
#include <timeapi.h>
#include <timezoneapi.h>
#include <tuple>
#include <tvout.h>
#include <type_traits>
#include <udpmib.h>
#include <unexposeenums2managed.h>
#include <unknwn.h>
#include <unknwnbase.h>
#include <unordered_map>
#include <urlmon.h>
#include <usb.h>
#include <usbfnbase.h>
#include <usbioctl.h>
#include <usbspec.h>
#include <utilapiset.h>
#include <utility>
#include <uuids.h>      // declaration of type GUIDs and well-known clsids"
#include <uxtheme.h>
#include <vcruntime.h>
#include <vcruntime_new_debug.h>
#include <vcruntime_startup.h>
#include <vcruntime_string.h>
#include <vdmctxt.h>
#include <vector>
//#include <veinterop_kcm.h>
//#include <verrsrc.h>
#include <version>
//#include <wabapi.h>
#include <wabcode.h>
//#include <wabdefs.h>
//#include <wabiab.h>
//#include <wabmem.h>
//#include <wabnot.h>
#include <wabtags.h>
//#include <wabutil.h>
//#include <wbemcli.h>
#include <wchar.h>
#if defined(NTDDI_WIN10_VB) && NTDDI_VERSION > NTDDI_WIN10_VB
#include <widemath.h>                // 64-bit and 128-bit math helper functions"
#endif
#include <winapifamily.h>
#include <winbase.h>
//#include <wincodec.h>
#include <wincon.h>
#include <wincontypes.h>
//#include <winddi.h>
///#include <winddiui.h>
#if defined(NTDDI_WIN10_VB) && NTDDI_VERSION > NTDDI_WIN10_VB
#include <windnsdef.h>
#endif
#include <windot11.h>
#include <windows.foundation.collections.h>
#include <windows.foundation.diagnostics.h>
#include <windows.foundation.h>
#include <windows.storage.streams.h>
#include <windows.graphics.effects.h>
#include <windowsx.h>
#include <winefs.h>
#include <winerror.h>
#include <wingdi.h>
#include <winmeta.h> // optional, used here for WINEVENT_LEVEL_ERROR"
#include <winnetwk.h>
#include <winnls.h>
#include <winnt.h>
#include <winnt.rh>
#include <winpackagefamily.h>
#include <winperf.h>    // necessary for the Detail Level definitions"
#include <winreg.h>
#include <winresrc.h>
#include <winscard.h>
#include <winsock.h>
#include <winspool.h>
#include <winsvc.h>     // SERVICE_STATUS_HANDLE"
#include <wintrust.h>
#include <winusbio.h>
#include <winuser.h>
#include <winuser.rh>
#include <winver.h>
//#include <wldp.h>
#include <wmistr.h>
//#include <wmiutils.h>
#include <wnnc.h>
#include <wow64apiset.h>
#include <wlclient.h>
#include <wtypes.h>
#include <wtypesbase.h>
#include <xmmintrin.h>
#include <yvals.h>
#include "ADOGuids.h"
#include "BdaTypes.h"
#include "DirectXMathConvert.inl"
#include "DirectXMathMatrix.inl"
#include "DirectXMathMisc.inl"
#include "DirectXMathVector.inl"
#include "EapAuthenticatorTypes.h"
#include "EapMethodTypes.h"
//#include "FRQuery.h"
//#include "FunctionDiscoveryAPI.h"
#include "FunctionDiscoveryCategories.h"
#include "FunctionDiscoveryConstraints.h"
#include "FunctionDiscoveryError.h"
#include "FunctionDiscoveryKeys.h"
//#include "FunctionDiscoveryNotification.h"
#include "FunctionDiscoveryServiceIDs.h"
#include "SessdirPublicTypes.h"
//#include "SpellCheck.h"
//#include "StructuredQuery.h"
#include "TpmVscAttestation.h"
//#include "VMRender.idl"
#include "VSStyle.h"
#include "VmSavedStateDumpDefs.h"
#include "WaaSAPITypes.h"
//#include "Wincodec.h"
#if defined(NTDDI_WIN10_VB) && NTDDI_VERSION > NTDDI_WIN10_VB
#include "Windows.AI.Actions.Hosting.h"
#include "Windows.AI.Actions.h"
#include "Windows.AI.Agents.h"
#endif
#include "Windows.ApplicationModel.Activation.h"
#include "Windows.ApplicationModel.AppService.h"
#include "Windows.ApplicationModel.Appointments.AppointmentsProvider.h"
#include "Windows.ApplicationModel.Appointments.h"
#include "Windows.ApplicationModel.Background.h"
#include "Windows.ApplicationModel.Calls.Background.h"
#include "Windows.ApplicationModel.Calls.h"
#include "Windows.ApplicationModel.CommunicationBlocking.h"
#include "Windows.ApplicationModel.Contacts.Provider.h"
#include "Windows.ApplicationModel.Contacts.h"
#include "Windows.ApplicationModel.Core.h"
#include "Windows.ApplicationModel.DataTransfer.DragDrop.h"
#include "Windows.ApplicationModel.DataTransfer.ShareTarget.h"
#include "Windows.ApplicationModel.DataTransfer.h"
#include "Windows.ApplicationModel.Email.h"
//#include "Windows.ApplicationModel.Payments.h"
#include "Windows.ApplicationModel.Search.h"
#include "Windows.ApplicationModel.SocialInfo.h"
#include "Windows.ApplicationModel.UserActivities.h"
#include "Windows.ApplicationModel.UserDataAccounts.Provider.h"
#include "Windows.ApplicationModel.UserDataAccounts.h"
#include "Windows.ApplicationModel.UserDataTasks.h"
#include "Windows.ApplicationModel.Wallet.h"
#include "Windows.ApplicationModel.h"
#include "Windows.Data.Json.h"
#include "Windows.Data.Text.h"
#include "Windows.Data.Xml.Dom.h"
#include "Windows.Devices.Adc.Provider.h"
#include "Windows.Devices.Bluetooth.Advertisement.h"
#include "Windows.Devices.Bluetooth.Background.h"
#include "Windows.Devices.Bluetooth.GenericAttributeProfile.h"
#include "Windows.Devices.Bluetooth.Rfcomm.h"
#include "Windows.Devices.Bluetooth.h"
#include "Windows.Devices.Display.h"
#include "Windows.Devices.Enumeration.h"
//#include "Windows.Devices.Geolocation.h"
#include "Windows.Devices.Gpio.Provider.h"
#include "Windows.Devices.Haptics.h"
#include "Windows.Devices.HumanInterfaceDevice.h"
#include "Windows.Devices.I2c.Provider.h"
#include "Windows.Devices.Input.h"
#include "Windows.Devices.Lights.h"
#include "Windows.Devices.Perception.h"
#include "Windows.Devices.PointOfService.h"
#include "Windows.Devices.Power.h"
#include "Windows.Devices.Printers.Extensions.h"
#include "Windows.Devices.Pwm.Provider.h"
#include "Windows.Devices.Radios.h"
#include "Windows.Devices.Sensors.h"
#include "Windows.Devices.SmartCards.h"
#include "Windows.Devices.Sms.h"
#include "Windows.Devices.Spi.Provider.h"
#include "Windows.Devices.h"
#include "Windows.Foundation.Numerics.h"
#include "Windows.Gaming.Input.Custom.h"
#include "Windows.Gaming.Input.ForceFeedback.h"
#include "Windows.Gaming.Input.h"
#include "Windows.Gaming.Preview.h"
#include "Windows.Gaming.XboxLive.h"
#include "Windows.Globalization.h"
#include "Windows.Management.Deployment.h"
#include "Windows.Media.Audio.h"
#include "Windows.Media.Capture.Core.h"
#include "Windows.Media.Capture.Frames.h"
#include "Windows.Media.Capture.h"
#include "Windows.Media.Casting.h"
#include "Windows.Media.Core.h"
#include "Windows.Media.Devices.Core.h"
#include "Windows.Media.Devices.h"
#include "Windows.Media.Editing.h"
#include "Windows.Media.Effects.h"
#include "Windows.Media.FaceAnalysis.h"
#include "Windows.Media.MediaProperties.h"
#include "Windows.Media.PlayTo.h"
#include "Windows.Media.Playback.h"
#include "Windows.Media.Protection.h"
#include "Windows.Media.Render.h"
#include "Windows.Media.SpeechRecognition.h"
#include "Windows.Media.Streaming.Adaptive.h"
#include "Windows.Media.Transcoding.h"
#include "Windows.Media.h"
#include "Windows.Networking.BackgroundTransfer.h"
#include "Windows.Networking.Connectivity.h"
#include "Windows.Networking.Sockets.h"
#include "Windows.Networking.h"
#include "Windows.Perception.People.h"
#include "Windows.Perception.Spatial.h"
#include "Windows.Perception.h"
#include "Windows.Phone.h"
#include "Windows.Security.Authentication.Web.Core.h"
#include "Windows.Security.Authentication.Web.Provider.h"
#include "Windows.Security.Authentication.Web.h"
#include "Windows.Security.Authorization.AppCapabilityAccess.h"
#include "Windows.Security.Credentials.h"
#include "Windows.Security.Cryptography.Certificates.h"
#include "Windows.Security.Cryptography.Core.h"
#include "Windows.Security.EnterpriseData.h"
#include "Windows.Services.Maps.LocalSearch.h"
#include "Windows.Services.Maps.h"
#include "Windows.Storage.FileProperties.h"
#include "Windows.Storage.Pickers.Provider.h"
#include "Windows.Storage.Provider.h"
#include "Windows.Storage.Search.h"
#include "Windows.Storage.h"
#include "Windows.System.Diagnostics.h"
#include "Windows.System.Power.h"
#include "Windows.System.RemoteSystems.h"
//#include "Windows.System.Threading.h"
#include "Windows.UI.Core.CoreWindowFactory.h"
#include "Windows.UI.Core.h"
#include "Windows.UI.Input.Inking.h"
#include "Windows.UI.Input.Spatial.h"
#include "Windows.UI.Input.h"
#include "Windows.UI.Notifications.h"
#include "Windows.UI.Popups.h"
#include "Windows.UI.Shell.h"
#include "Windows.UI.StartScreen.h"
#include "Windows.UI.Text.Core.h"
#include "Windows.UI.Text.h"
#if defined(NTDDI_WIN10_VB) && NTDDI_VERSION > NTDDI_WIN10_VB
#include "Windows.UI.UIAutomation.h"
#endif
#include "Windows.UI.ViewManagement.h"
#include "Windows.UI.WindowManagement.h"
#include "Windows.Web.Http.Filters.h"
#include "Windows.Web.Http.Headers.h"
#include "Windows.Web.Http.h"
#include "Windows.Web.Syndication.h"
#include "Windows.Web.UI.h"
#include "Windows.Web.h"
//#include "activeds.h"
#include "activscp.h"
#include "adodef.h"
//#include "adoint_backcompat.h"
#include "adsdb.h"
#include "adserr.h"
//#include "adshlp.h"
#include "adsiid.h"
#include "adsnms.h"
#include "adssts.h"
#include "asferr.h"
#include "audioapotypes.h"
//#include "axcore.idl"
#include "basetsd.h"
//#include "bits.h"
#include "bitsmsg.h"
#include "cdosysstr.h"
#include "certbase.h"
#include "comadmin.h"
#include "commctrl.inl"
#include "commdlg.inl"
//#include "comsvcs.h"

//#include "dbgprop.h"
//#include "dbs.idl"
//#include "dbsdep.idl"
//#include "devenum.idl"
#include "dbgprop.h"
//#include "exdisp.h"
#include "exdispid.h"
#include "mddefw.h"
//#include "mmc.h"
//#include "propidlbase.idl"
#include "prsht.inl"
//#include "sapiaut.idl"
#include "sdv_driverspecs.h"
//#include "srchntfyinlinesite.idl"
//#include "srchprth.idl"
#include "stgprop.h"
//#include "stm.h"
#include "transportsettingcommon.h"
#include "utillib.h"
#include "vsserror.h"
#include "winsmcrd.h"
#include "winuser.inl"
#include "wsdxmldom.h"
#include "xmldomdid.h"